### ISSUE TITLE
现代C++中IO、字符串和正则表达式库的性能，提升还是原地踏步?

### ISSUE THREAD

**Issue by longlongvip** [changkun/cpp1x-tutorial#300]
## 问题描述

现代C++中IO、字符串和正则表达式库的性能，提升还是原地踏步?

**Comment by frederick-vs-ja** [comment]
大概是和本书无关的内容。

目前看来正则表达式部分只能原地踏步——进一步的优化需要破坏 ABI 兼容。其他部分算是相对容易优化的，并且确实有人在做优化。

**Comment by longlongvip** [comment]
> 大概是和本书无关的内容。
> 
> 目前看来正则表达式部分只能原地踏步——进一步的优化需要破坏 ABI 兼容。其他部分算是相对容易优化的，并且确实有人在做优化。

了解，我主要是看本书中有推荐使用正则表达式
